{
  "openapi": "3.0.0",
  "info": {
    "title": "secure.na3.adobesign.com",
    "version": "6.0.0"
  },
  "servers": [
    {
      "url": "https://secure.na3.adobesign.com/api/rest/v6"
    }
  ],
  "paths": {
    "/agreements": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreements",
        "summary": "Retrieves agreements for the user."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "This is a primary endpoint which is used to create a new agreement. An agreement can be created using transientDocument, libraryDocument or a URL. You can create an agreement in one of the 3 mentioned states: a) <b>DRAFT</b> - to incrementally build the agreement before sending out, b) <b>AUTHORING</b> - to add/edit form fields in the agreement, c) <b>IN_PROCESS</b> - to immediately send the agreement. You can use the PUT /agreements/{agreementId}/state endpoint to transi[...]",
        "operationId": "createAgreement",
        "summary": "Creates an agreement. Sends it out for signatures, and returns the agreementID in the response to the client."
      }
    },
    "/agreements/{agreementId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementInfo",
        "summary": "Retrieves the current status of an agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateAgreement",
        "summary": "Updates the agreement in draft state, or update the expirationTime on an existing agreement that is already out for signature."
      }
    },
    "/agreements/{agreementId}/auditTrail": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "PDF file stream containing audit trail information",
        "operationId": "getAuditTrail",
        "summary": "Retrieves the audit trail of an agreement identified by agreementId."
      }
    },
    "/agreements/{agreementId}/combinedDocument": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getCombinedDocument",
        "summary": "Retrieves a single combined PDF document for the documents associated with an agreement."
      }
    },
    "/agreements/{agreementId}/combinedDocument/pagesInfo": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getCombinedDocumentPagesInfo",
        "summary": "Retrieves info of all pages of a combined PDF document for the documents associated with an agreement."
      }
    },
    "/agreements/{agreementId}/combinedDocument/url": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getCombinedDocumentUrl",
        "summary": "Retrieves url of all visible pages of all the documents associated with an agreement."
      }
    },
    "/agreements/{agreementId}/documents": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "agreement_retention"
            ]
          }
        ],
        "operationId": "deleteDocuments",
        "summary": "Deletes all the documents of an agreement."
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAllDocuments",
        "summary": "Retrieves the IDs of the documents of an agreement identified by agreementId."
      }
    },
    "/agreements/{agreementId}/documents/imageUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAllDocumentsImageUrls",
        "summary": "Retrieves image urls of all visible pages of all the documents associated with an agreement."
      }
    },
    "/agreements/{agreementId}/documents/{documentId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getDocument",
        "summary": "Retrieves the file stream of a document of an agreement."
      }
    },
    "/agreements/{agreementId}/documents/{documentId}/imageUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getDocumentImageUrls",
        "summary": "Retrieves image urls of all visible pages of a document associated with an agreement."
      }
    },
    "/agreements/{agreementId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getEvents",
        "summary": "Retrieves the events information for an agreement."
      }
    },
    "/agreements/{agreementId}/formData": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "This API can only be called by the creator of the agreement",
        "operationId": "getFormData",
        "summary": "Retrieves data entered into the interactive form fields of the agreement."
      }
    },
    "/agreements/{agreementId}/formFields": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getFormFields",
        "summary": "Retrieves details of form fields of an agreement."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "addTemplateFieldsToAgreement",
        "summary": "Adds template fields to an agreement"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateFormFields",
        "summary": "Updates form fields of an agreement.  This will replace all fields in AUTHORING mode agreements, and will replace all fields except for text tag generated fields in DRAFT mode agreements."
      }
    },
    "/agreements/{agreementId}/formFields/mergeInfo": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMergeInfo",
        "summary": "Retrieves the merge info stored with an agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateAgreementMergeInfo",
        "summary": "Set the merge info for an agreement."
      }
    },
    "/agreements/{agreementId}/me": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementInfoForUser",
        "summary": "Retrieves the agreement information related to the api caller"
      }
    },
    "/agreements/{agreementId}/me/note": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementNoteForApiUser",
        "summary": "Retrieves the latest note associated with an agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateAgreementNoteForApiUser",
        "summary": "Updates the latest note associated with an agreement."
      }
    },
    "/agreements/{agreementId}/me/visibility": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateAgreementVisibility",
        "summary": "Updates the visibility of an agreement."
      }
    },
    "/agreements/{agreementId}/members": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAllMembers",
        "summary": "Retrieves information of members of the agreement."
      }
    },
    "/agreements/{agreementId}/members/participantSets/{participantSetId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getParticipantSet",
        "summary": "Retrieves the participant set of an agreement identified by agreementId in the path."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateParticipantSet",
        "summary": "Updates the participant set of an agreement identified by agreementId in the path."
      }
    },
    "/agreements/{agreementId}/members/participantSets/{participantSetId}/delegatedParticipantSets": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "Participants marked as delegator can call this API endpoint.",
        "operationId": "createDelegatedParticipantSets",
        "summary": "Creates a participantSet to which the agreement is forwarded for taking appropriate action."
      }
    },
    "/agreements/{agreementId}/members/participantSets/{participantSetId}/participants/{participantId}/reject": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "rejectAgreementForParticipation",
        "summary": "Rejects the agreement for a participant."
      }
    },
    "/agreements/{agreementId}/members/participantSets/{participantSetId}/participants/{participantId}/securityOptions": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementSecurityOptionsForParticipation",
        "summary": "Retrieves the security options for a particular participant."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateAgreementSecurityOptionsForParticipation",
        "summary": "Updates the security options for a particular participant."
      }
    },
    "/agreements/{agreementId}/members/share": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "createShareOnAgreement",
        "summary": "Share an agreement with someone."
      }
    },
    "/agreements/{agreementId}/reminders": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementReminders",
        "summary": "Retrieves the reminders of an agreement, identified by agreementId in the path."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "createReminderOnParticipant",
        "summary": "Creates a reminder on the specified participants of an agreement identified by agreementId in the path."
      }
    },
    "/agreements/{agreementId}/reminders/{reminderId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementReminder",
        "summary": "Retrieves a specific reminder associated with an agreement"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "You can only update an ACTIVE reminder, and can only update the status to 'CANCELED', update reminderParticipantIds, or update note.",
        "operationId": "updateAgreementReminder",
        "summary": "Updates an existing reminder for an agreement"
      }
    },
    "/agreements/{agreementId}/sender": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "changeAgreementOwner",
        "summary": "This API can change sender for an agreement that has status of draft"
      }
    },
    "/agreements/{agreementId}/settings": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementSettings",
        "summary": "Get the settings for the agreement"
      }
    },
    "/agreements/{agreementId}/signerIdentityReport": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "PDF file stream containing signer identify information",
        "operationId": "createSignerIdentityReport",
        "summary": "Retrieves the signer identity report of an agreement identified by agreementId."
      }
    },
    "/agreements/{agreementId}/signingUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "getSigningUrl",
        "summary": "Retrieves the URL for the e-sign page for the current signer(s) of an agreement."
      }
    },
    "/agreements/{agreementId}/state": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "This endpoint can be used by originator/sender of an agreement to transition between the states of agreement. An allowed transition would follow the following sequence: DRAFT -> AUTHORING -> IN_PROCESS -> CANCELLED.",
        "operationId": "updateAgreementState",
        "summary": "Updates the state of an agreement identified by agreementId in the path."
      }
    },
    "/agreements/{agreementId}/vaulted": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_vault"
            ]
          }
        ],
        "operationId": "updateAgreementVaulted",
        "summary": "Complete the vaulting process and update the agreement as vaulted."
      }
    },
    "/agreements/{agreementId}/views": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_read",
              "user_login"
            ]
          }
        ],
        "operationId": "createAgreementView",
        "summary": "Retrieves the latest state view url of agreement."
      }
    }
  },
  "components": {
  }
}
