{
  "openapi": "3.0.0",
  "info": {
    "title": "secure.na3.adobesign.com",
    "version": "6.0.0"
  },
  "servers": [
    {
      "url": "https://secure.na3.adobesign.com/api/rest/v6"
    }
  ],
  "paths": {
    "/megaSigns": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSigns",
        "summary": "Retrieves Send in Bulk parent agreements for a user."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "This is a primary endpoint which is used to create a new bulk send. A bulk send can be created using transientDocument, libraryDocument or a URL. You can create a bulk send in <b>AUTHORING</b> state to prepare the document before send or in <b>IN_PROCESS</b> to immediately send it. You can use the PUT/megaSigns/{megaSignId}/state endpoint to transition the state of bulk send. An allowed transition would follow the following sequence: AUTHORING->IN_PROCESS -> CANCELLED.",
        "operationId": "createMegaSign",
        "summary": "Send an agreement out for signature to multiple recipients. Each recipient will receive and sign their own copy of the agreement."
      }
    },
    "/megaSigns/{megaSignId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignInfo",
        "summary": "Get detailed information of the specified Send in Bulk parent agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateMegaSign",
        "summary": "Update the expirationTime on an existing bulk send parent and all the child agreements that are already out for signature."
      }
    },
    "/megaSigns/{megaSignId}/agreements": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignChildAgreements",
        "summary": "Get all the child agreements of the specified Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/childAgreementsInfo/{childAgreementsInfoFileId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "CSV file stream containing form data information",
        "operationId": "getChildAgreementsInfoFile",
        "summary": "Retrieves the file stream of the original childAgreementsInfoFile that was uploaded by sender while creating the Send in Bulk."
      }
    },
    "/megaSigns/{megaSignId}/combinedDocument": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignCombinedDocument",
        "summary": "Retrieves a single combined PDF document for the documents associated with the Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/combinedDocument/url": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignCombinedDocumentUrl",
        "summary": "Retrieves url of all visible pages of all the documents associated with the Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/documents": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignAllDocuments",
        "summary": "Retrieves the IDs of the documents associated with a Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/documents/imageUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignAllDocumentsImageUrls",
        "summary": "Retrieves image urls of all visible pages of a document associated with a Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/documents/{documentId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "Raw stream of the file",
        "operationId": "getMegaSignDocumentInfo",
        "summary": "Retrieves the file stream of a document of a Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getEvents",
        "summary": "Retrieves the events information for the Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/formData": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "CSV/JSON file stream containing form data information",
        "operationId": "getMegaSignFormData",
        "summary": "Retrieves data entered by recipients into interactive form fields at the time they signed the child agreements of the specified Send in Bulk agreement"
      }
    },
    "/megaSigns/{megaSignId}/formFields": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getFormFields",
        "summary": "Retrieves details of form fields of a Send in Bulk parent agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateFormFields",
        "summary": "Updates the details of form fields of a Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/me": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignInfoForUser",
        "summary": "Retrieves the Send in Bulk parent agreement information related to the api caller"
      }
    },
    "/megaSigns/{megaSignId}/me/note": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignNoteForUser",
        "summary": "Retrieves the latest note of a Send in Bulk parent agreement for the user."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateMegaSignNoteForUser",
        "summary": "Updates the latest note of a Send in Bulk parent agreement for the user."
      }
    },
    "/megaSigns/{megaSignId}/me/visibility": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateMegaSignVisibility",
        "summary": "Updates the visibility of a bulk send."
      }
    },
    "/megaSigns/{megaSignId}/members": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAllMegaSignMembers",
        "summary": "Retrieves detailed member info along with IDs for different types of participants associated with the Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/members/share": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "createShareOnMegaSign",
        "summary": "Share a bulk send parent and all the child agreements with someone."
      }
    },
    "/megaSigns/{megaSignId}/reminders": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignReminders",
        "summary": "Retrieves the reminders of the specified Send in Bulk parent agreement."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "createReminderOnMegaSign",
        "summary": "Creates a reminder on the specified participants of the bulk send parent."
      }
    },
    "/megaSigns/{megaSignId}/reminders/{reminderId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignReminder",
        "summary": "Retrieves a specific reminder given the reminder id for the specified Send in Bulk parent agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "You can only update an ACTIVE reminder, and can only update the status to 'CANCELED', update reminderParticipantIds, update allUnsigned or update note.",
        "operationId": "updateMegaSignReminder",
        "summary": "Updates an existing reminder for a Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/state": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "This endpoint can be used by creator of the bulk send to transition between the states of a bulk send. An allowed transition would follow the following sequence :  AUTHORING->IN_PROCESS->CANCELLED.",
        "operationId": "updateMegaSignState",
        "summary": "Updates the state of a bulk send identified by MegaSignId in the path."
      }
    },
    "/megaSigns/{megaSignId}/views": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_read",
              "user_login"
            ]
          }
        ],
        "operationId": "getMegaSignView",
        "summary": "Retrieves the requested views of a bulk send agreement."
      }
    }
  },
  "components": {
  }
}
