{
  "openapi": "3.0.3",
  "info": {
    "title": "secure.na3.adobesign.com",
    "version": "6.0.0"
  },
  "servers": [
    {
      "url": "https://secure.na3.adobesign.com/api/rest/v6"
    }
  ],
  "paths": {
    "/accounts": {
      "post": {
        "security": [
          {
            "oauth2": [
              "account_write"
            ]
          }
        ],
        "operationId": "createAccount",
        "summary": "Creates an Acrobat Sign account under the partner channel"
      }
    },
    "/accounts/{accountId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getAccount",
        "summary": "Retrieves the information for an account."
      }
    },
    "/accounts/{accountId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getAccountEvents",
        "summary": "Retrieves all events for account"
      }
    },
    "/agreements": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreements",
        "summary": "Retrieves agreements for the user."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "This is a primary endpoint which is used to create a new agreement. An agreement can be created using transientDocument, libraryDocument or a URL. You can create an agreement in one of the 3 mentioned states: a) <b>DRAFT</b> - to incrementally build the agreement before sending out, b) <b>AUTHORING</b> - to add/edit form fields in the agreement, c) <b>IN_PROCESS</b> - to immediately send the agreement. You can use the PUT /agreements/{agreementId}/state endpoint to transi[...]",
        "operationId": "createAgreement",
        "summary": "Creates an agreement. Sends it out for signatures, and returns the agreementID in the response to the client."
      }
    },
    "/agreements/{agreementId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementInfo",
        "summary": "Retrieves the current status of an agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateAgreement",
        "summary": "Updates the agreement in draft state, or update the expirationTime on an existing agreement that is already out for signature."
      }
    },
    "/agreements/{agreementId}/auditTrail": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "PDF file stream containing audit trail information",
        "operationId": "getAuditTrail",
        "summary": "Retrieves the audit trail of an agreement identified by agreementId."
      }
    },
    "/agreements/{agreementId}/combinedDocument": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getCombinedDocument",
        "summary": "Retrieves a single combined PDF document for the documents associated with an agreement."
      }
    },
    "/agreements/{agreementId}/combinedDocument/pagesInfo": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getCombinedDocumentPagesInfo",
        "summary": "Retrieves info of all pages of a combined PDF document for the documents associated with an agreement."
      }
    },
    "/agreements/{agreementId}/combinedDocument/url": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getCombinedDocumentUrl",
        "summary": "Retrieves url of all visible pages of all the documents associated with an agreement."
      }
    },
    "/agreements/{agreementId}/documents": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "agreement_retention"
            ]
          }
        ],
        "operationId": "deleteDocuments",
        "summary": "Deletes all the documents of an agreement."
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAllDocuments",
        "summary": "Retrieves the IDs of the documents of an agreement identified by agreementId."
      }
    },
    "/agreements/{agreementId}/documents/imageUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAllDocumentsImageUrls",
        "summary": "Retrieves image urls of all visible pages of all the documents associated with an agreement."
      }
    },
    "/agreements/{agreementId}/documents/{documentId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getDocument",
        "summary": "Retrieves the file stream of a document of an agreement."
      }
    },
    "/agreements/{agreementId}/documents/{documentId}/imageUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getDocumentImageUrls",
        "summary": "Retrieves image urls of all visible pages of a document associated with an agreement."
      }
    },
    "/agreements/{agreementId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getEvents",
        "summary": "Retrieves the events information for an agreement."
      }
    },
    "/agreements/{agreementId}/formData": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "This API can only be called by the creator of the agreement",
        "operationId": "getFormData",
        "summary": "Retrieves data entered into the interactive form fields of the agreement."
      }
    },
    "/agreements/{agreementId}/formFields": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getFormFields",
        "summary": "Retrieves details of form fields of an agreement."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "addTemplateFieldsToAgreement",
        "summary": "Adds template fields to an agreement"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateFormFields",
        "summary": "Updates form fields of an agreement.  This will replace all fields in AUTHORING mode agreements, and will replace all fields except for text tag generated fields in DRAFT mode agreements."
      }
    },
    "/agreements/{agreementId}/formFields/mergeInfo": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMergeInfo",
        "summary": "Retrieves the merge info stored with an agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateAgreementMergeInfo",
        "summary": "Set the merge info for an agreement."
      }
    },
    "/agreements/{agreementId}/me": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementInfoForUser",
        "summary": "Retrieves the agreement information related to the api caller"
      }
    },
    "/agreements/{agreementId}/me/note": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementNoteForApiUser",
        "summary": "Retrieves the latest note associated with an agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateAgreementNoteForApiUser",
        "summary": "Updates the latest note associated with an agreement."
      }
    },
    "/agreements/{agreementId}/me/visibility": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateAgreementVisibility",
        "summary": "Updates the visibility of an agreement."
      }
    },
    "/agreements/{agreementId}/members": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAllMembers",
        "summary": "Retrieves information of members of the agreement."
      }
    },
    "/agreements/{agreementId}/members/participantSets/{participantSetId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getParticipantSet",
        "summary": "Retrieves the participant set of an agreement identified by agreementId in the path."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateParticipantSet",
        "summary": "Updates the participant set of an agreement identified by agreementId in the path."
      }
    },
    "/agreements/{agreementId}/members/participantSets/{participantSetId}/delegatedParticipantSets": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "Participants marked as delegator can call this API endpoint.",
        "operationId": "createDelegatedParticipantSets",
        "summary": "Creates a participantSet to which the agreement is forwarded for taking appropriate action."
      }
    },
    "/agreements/{agreementId}/members/participantSets/{participantSetId}/participants/{participantId}/reject": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "rejectAgreementForParticipation",
        "summary": "Rejects the agreement for a participant."
      }
    },
    "/agreements/{agreementId}/members/participantSets/{participantSetId}/participants/{participantId}/securityOptions": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementSecurityOptionsForParticipation",
        "summary": "Retrieves the security options for a particular participant."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateAgreementSecurityOptionsForParticipation",
        "summary": "Updates the security options for a particular participant."
      }
    },
    "/agreements/{agreementId}/members/share": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "createShareOnAgreement",
        "summary": "Share an agreement with someone."
      }
    },
    "/agreements/{agreementId}/reminders": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementReminders",
        "summary": "Retrieves the reminders of an agreement, identified by agreementId in the path."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "createReminderOnParticipant",
        "summary": "Creates a reminder on the specified participants of an agreement identified by agreementId in the path."
      }
    },
    "/agreements/{agreementId}/reminders/{reminderId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementReminder",
        "summary": "Retrieves a specific reminder associated with an agreement"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "You can only update an ACTIVE reminder, and can only update the status to 'CANCELED', update reminderParticipantIds, or update note.",
        "operationId": "updateAgreementReminder",
        "summary": "Updates an existing reminder for an agreement"
      }
    },
    "/agreements/{agreementId}/sender": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "changeAgreementOwner",
        "summary": "This API can change sender for an agreement that has status of draft"
      }
    },
    "/agreements/{agreementId}/settings": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAgreementSettings",
        "summary": "Get the settings for the agreement"
      }
    },
    "/agreements/{agreementId}/signerIdentityReport": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "PDF file stream containing signer identify information",
        "operationId": "createSignerIdentityReport",
        "summary": "Retrieves the signer identity report of an agreement identified by agreementId."
      }
    },
    "/agreements/{agreementId}/signingUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "getSigningUrl",
        "summary": "Retrieves the URL for the e-sign page for the current signer(s) of an agreement."
      }
    },
    "/agreements/{agreementId}/state": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "This endpoint can be used by originator/sender of an agreement to transition between the states of agreement. An allowed transition would follow the following sequence: DRAFT -> AUTHORING -> IN_PROCESS -> CANCELLED.",
        "operationId": "updateAgreementState",
        "summary": "Updates the state of an agreement identified by agreementId in the path."
      }
    },
    "/agreements/{agreementId}/vaulted": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_vault"
            ]
          }
        ],
        "operationId": "updateAgreementVaulted",
        "summary": "Complete the vaulting process and update the agreement as vaulted."
      }
    },
    "/agreements/{agreementId}/views": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_read",
              "user_login"
            ]
          }
        ],
        "operationId": "createAgreementView",
        "summary": "Retrieves the latest state view url of agreement."
      }
    },
    "/baseUris": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read",
              "agreement_sign",
              "agreement_vault",
              "agreement_write",
              "agreement_retention",
              "library_read",
              "library_write",
              "library_retention",
              "user_login",
              "user_read",
              "account_read",
              "account_write",
              "user_write",
              "widget_read",
              "widget_write",
              "widget_sign",
              "application_read",
              "application_write",
              "agreement_send",
              "workflow_read",
              "webhook_read",
              "webhook_write",
              "webhook_retention"
            ]
          }
        ],
        "operationId": "getBaseUris",
        "summary": "Gets the base uri to access other APIs. In case other APIs are accessed from a different end point, it will be considered an invalid request."
      }
    },
    "/groups": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getGroups",
        "summary": "Retrieves all the groups in an account."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "createGroup",
        "summary": "Creates a new group in an account."
      }
    },
    "/groups/{groupId}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "deleteGroup",
        "summary": "Delete an existing group."
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getGroupDetails",
        "summary": "Retrieves detailed information about the group."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "modifyGroup",
        "summary": "Update an existing group."
      }
    },
    "/groups/{groupId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getGroupEvents",
        "summary": "Retrieves all events for group"
      }
    },
    "/groups/{groupId}/users": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getUsersInGroup",
        "summary": "Retrieves all the users in a group."
      }
    },
    "/libraryDocuments": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getLibraryDocuments",
        "summary": "Retrieves library documents for a user."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "library_write"
            ]
          }
        ],
        "operationId": "createLibraryDocument",
        "summary": "Creates a template that is placed in the library of the user for reuse."
      }
    },
    "/libraryDocuments/{libraryDocumentId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getLibraryDocumentInfo",
        "summary": "Retrieves the details of a library document."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "library_write"
            ]
          }
        ],
        "description": "Currently status, name, sharingMode and templateTypes of the library document can only be updated.",
        "operationId": "updateLibraryDocument",
        "summary": "Updates the library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/auditTrail": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getLibraryDocumentAuditTrail",
        "summary": "Retrieves the audit trail associated with a library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/combinedDocument": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getCombinedDocument1",
        "summary": "Retrieves the combined document associated with a library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/combinedDocument/url": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getLibraryCombinedDocumentUrl",
        "summary": "Retrieves url of all visible pages of all the documents associated with a library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/documents": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getDocuments",
        "summary": "Retrieves the IDs of the documents associated with library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/documents/{documentId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getLibraryDocument",
        "summary": "Retrieves the file stream of a document of library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/documents/{documentId}/imageUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getLibraryDocumentImageUrls",
        "summary": "Retrieves image urls of all visible pages of a document associated with a library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getEvents1",
        "summary": "Retrieves the events information for a library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/formData": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "description": "This API can only be called by the creator of the library document",
        "operationId": "getFormData1",
        "summary": "Retrieves data entered into the interactive form fields of the library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/formFields": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getFormFields1",
        "summary": "Retrieves details of form fields of a library document."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "library_write"
            ]
          }
        ],
        "operationId": "updateFormFields1",
        "summary": "Updates details of form fields of a library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/me": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getLibraryDocumentInfoForUser",
        "summary": "Retrieves the library document information related to the api caller"
      }
    },
    "/libraryDocuments/{libraryDocumentId}/me/note": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getLibraryDocumentNoteForApiUser",
        "summary": "Retrieves the latest note of a library document for the API user."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "library_write"
            ]
          }
        ],
        "operationId": "updateLibraryDocumentNoteForApiUser",
        "summary": "Updates the latest note of a library document for the API user."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/me/visibility": {
      "put": {
        "security": [
          {
            "oauth2": [
              "library_write"
            ]
          }
        ],
        "operationId": "updateLibraryDocumentVisibility",
        "summary": "Updates the visibility of library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/members": {
      "get": {
        "security": [
          {
            "oauth2": [
              "library_read"
            ]
          }
        ],
        "operationId": "getAllLibraryDocumentMembers",
        "summary": "Retrieves information of members (creator) of the library document."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/state": {
      "put": {
        "security": [
          {
            "oauth2": [
              "library_write"
            ]
          }
        ],
        "description": "Currently state can be changed from AUTHORING to ACTIVE, AUTHORING to REMOVED or ACTIVE to REMOVED",
        "operationId": "updateLibraryDocumentState",
        "summary": "Updates the library document's state."
      }
    },
    "/libraryDocuments/{libraryDocumentId}/views": {
      "post": {
        "security": [
          {
            "oauth2": [
              "library_read",
              "user_login"
            ]
          }
        ],
        "operationId": "createLibraryDocumentView",
        "summary": "Retrieves the latest state view url of a library document."
      }
    },
    "/megaSigns": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSigns",
        "summary": "Retrieves Send in Bulk parent agreements for a user."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "This is a primary endpoint which is used to create a new bulk send. A bulk send can be created using transientDocument, libraryDocument or a URL. You can create a bulk send in <b>AUTHORING</b> state to prepare the document before send or in <b>IN_PROCESS</b> to immediately send it. You can use the PUT/megaSigns/{megaSignId}/state endpoint to transition the state of bulk send. An allowed transition would follow the following sequence: AUTHORING->IN_PROCESS -> CANCELLED.",
        "operationId": "createMegaSign",
        "summary": "Send an agreement out for signature to multiple recipients. Each recipient will receive and sign their own copy of the agreement."
      }
    },
    "/megaSigns/{megaSignId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignInfo",
        "summary": "Get detailed information of the specified Send in Bulk parent agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateMegaSign",
        "summary": "Update the expirationTime on an existing bulk send parent and all the child agreements that are already out for signature."
      }
    },
    "/megaSigns/{megaSignId}/agreements": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignChildAgreements",
        "summary": "Get all the child agreements of the specified Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/childAgreementsInfo/{childAgreementsInfoFileId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "CSV file stream containing form data information",
        "operationId": "getChildAgreementsInfoFile",
        "summary": "Retrieves the file stream of the original childAgreementsInfoFile that was uploaded by sender while creating the Send in Bulk."
      }
    },
    "/megaSigns/{megaSignId}/combinedDocument": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignCombinedDocument",
        "summary": "Retrieves a single combined PDF document for the documents associated with the Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/combinedDocument/url": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignCombinedDocumentUrl",
        "summary": "Retrieves url of all visible pages of all the documents associated with the Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/documents": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignAllDocuments",
        "summary": "Retrieves the IDs of the documents associated with a Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/documents/imageUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignAllDocumentsImageUrls",
        "summary": "Retrieves image urls of all visible pages of a document associated with a Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/documents/{documentId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "Raw stream of the file",
        "operationId": "getMegaSignDocumentInfo",
        "summary": "Retrieves the file stream of a document of a Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getEvents2",
        "summary": "Retrieves the events information for the Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/formData": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "description": "CSV/JSON file stream containing form data information",
        "operationId": "getMegaSignFormData",
        "summary": "Retrieves data entered by recipients into interactive form fields at the time they signed the child agreements of the specified Send in Bulk agreement"
      }
    },
    "/megaSigns/{megaSignId}/formFields": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getFormFields2",
        "summary": "Retrieves details of form fields of a Send in Bulk parent agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateFormFields2",
        "summary": "Updates the details of form fields of a Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/me": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignInfoForUser",
        "summary": "Retrieves the Send in Bulk parent agreement information related to the api caller"
      }
    },
    "/megaSigns/{megaSignId}/me/note": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignNoteForUser",
        "summary": "Retrieves the latest note of a Send in Bulk parent agreement for the user."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateMegaSignNoteForUser",
        "summary": "Updates the latest note of a Send in Bulk parent agreement for the user."
      }
    },
    "/megaSigns/{megaSignId}/me/visibility": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "updateMegaSignVisibility",
        "summary": "Updates the visibility of a bulk send."
      }
    },
    "/megaSigns/{megaSignId}/members": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getAllMegaSignMembers",
        "summary": "Retrieves detailed member info along with IDs for different types of participants associated with the Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/members/share": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "createShareOnMegaSign",
        "summary": "Share a bulk send parent and all the child agreements with someone."
      }
    },
    "/megaSigns/{megaSignId}/reminders": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignReminders",
        "summary": "Retrieves the reminders of the specified Send in Bulk parent agreement."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "operationId": "createReminderOnMegaSign",
        "summary": "Creates a reminder on the specified participants of the bulk send parent."
      }
    },
    "/megaSigns/{megaSignId}/reminders/{reminderId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "agreement_read"
            ]
          }
        ],
        "operationId": "getMegaSignReminder",
        "summary": "Retrieves a specific reminder given the reminder id for the specified Send in Bulk parent agreement."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "You can only update an ACTIVE reminder, and can only update the status to 'CANCELED', update reminderParticipantIds, update allUnsigned or update note.",
        "operationId": "updateMegaSignReminder",
        "summary": "Updates an existing reminder for a Send in Bulk parent agreement."
      }
    },
    "/megaSigns/{megaSignId}/state": {
      "put": {
        "security": [
          {
            "oauth2": [
              "agreement_write"
            ]
          }
        ],
        "description": "This endpoint can be used by creator of the bulk send to transition between the states of a bulk send. An allowed transition would follow the following sequence :  AUTHORING->IN_PROCESS->CANCELLED.",
        "operationId": "updateMegaSignState",
        "summary": "Updates the state of a bulk send identified by MegaSignId in the path."
      }
    },
    "/megaSigns/{megaSignId}/views": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_read",
              "user_login"
            ]
          }
        ],
        "operationId": "getMegaSignView",
        "summary": "Retrieves the requested views of a bulk send agreement."
      }
    },
    "/messageTemplates": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getMessageTemplates",
        "summary": "Retrieves a list of message templates applicable to the current user."
      }
    },
    "/search": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_read",
              "library_read",
              "widget_read"
            ]
          }
        ],
        "operationId": "searchResources",
        "summary": "Retrieves, searches, filters, and sorts agreements for the user."
      }
    },
    "/transientDocuments": {
      "post": {
        "security": [
          {
            "oauth2": [
              "agreement_write",
              "agreement_sign",
              "widget_write",
              "library_write"
            ]
          }
        ],
        "description": "The document uploaded through this call is referred to as transient since it is available only for 7 days after the upload. The returned transient document ID can be used in the API calls where the uploaded file needs to be referred. The transient document request is a multipart request consisting of three parts - filename, mime type and the file stream. You can only upload one file at a time in this request.",
        "operationId": "createTransientDocument",
        "summary": "Uploads a document and obtains the document's ID."
      }
    },
    "/users": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getUsers",
        "summary": "Retrieves all the users in an account."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "createUser",
        "summary": "Creates a new user in the Acrobat Sign system"
      }
    },
    "/users/{userId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getUserDetail",
        "summary": "Retrieves detailed information about the user in the caller account."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "modifyUser",
        "summary": "Update an user."
      }
    },
    "/users/{userId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getUserEvents",
        "summary": "Retrieves all events for user"
      }
    },
    "/users/{userId}/groups": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getGroupsOfUser",
        "summary": "Retrieves the groups of the user."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "updateGroupsOfUser",
        "summary": "Updates the groups of the user."
      }
    },
    "/users/{userId}/locale": {
      "put": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "modifyUserLocale",
        "summary": "Updates the user locale."
      }
    },
    "/users/{userId}/state": {
      "put": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "modifyUserState",
        "summary": "Activate/Deactivate a given user."
      }
    },
    "/users/{userId}/views": {
      "post": {
        "security": [
          {
            "oauth2": [
              "user_read",
              "user_login"
            ]
          }
        ],
        "operationId": "getUserViews",
        "summary": "Retrieves the URL of manage, account settings and user profile page."
      }
    },
    "/webhooks": {
      "get": {
        "security": [
          {
            "oauth2": [
              "webhook_read"
            ]
          }
        ],
        "operationId": "getWebhooks",
        "summary": "Retrieves webhooks for a user."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "webhook_write"
            ]
          }
        ],
        "description": "This is a primary endpoint which is used to create a new webhook. A webhook can only be created in ACTIVE state. Currently, webhooks are supported at four scopes - Account, Group, User and Resource. <br/> <br/> Before creating a webhook successfully at any of these scopes, Acrobat Sign <a href='https://www.adobe.io/apis/documentcloud/sign/docs.html#!adobedocs/adobe-sign/master/webhooks.md#verificationofintentofthewebhookurl'>verifies</a> that the webhook URL that is provi[...]",
        "operationId": "createWebhook",
        "summary": "Creates a webhook."
      }
    },
    "/webhooks/{webhookId}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "webhook_retention"
            ]
          }
        ],
        "operationId": "deleteWebhook",
        "summary": "Deletes a webhook."
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "webhook_read"
            ]
          }
        ],
        "operationId": "getWebhookInfo",
        "summary": "Retrieves the details of a webhook."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "webhook_write"
            ]
          }
        ],
        "operationId": "updateWebhook",
        "summary": "Updates a webhook."
      }
    },
    "/webhooks/{webhookId}/state": {
      "put": {
        "security": [
          {
            "oauth2": [
              "webhook_write"
            ]
          }
        ],
        "operationId": "updateWebhookState",
        "summary": "Updates the state of a webhook identified by webhookId in the path."
      }
    },
    "/widgets": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgets",
        "summary": "Retrieves web forms for a user."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "description": "This is a primary endpoint which is used to create a new web form. You can create a web form in one of the 3 mentioned states: a) <b>DRAFT</b> - to incrementally build the web form, b) <b>AUTHORING</b> - to add/edit form fields in the web form, c) <b>ACTIVE</b> - to immediately host the web form. You can use the PUT /widgets/{widgetId}/state endpoint to transition a web form between the above mentioned states. An allowed transition would follow the any of the following se[...]",
        "operationId": "createWidget",
        "summary": "Creates a web form and and returns the widgetId in the response to the client."
      }
    },
    "/widgets/{widgetId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetInfo",
        "summary": "Retrieves the details of a web form."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidget",
        "summary": "Updates a web form."
      }
    },
    "/widgets/{widgetId}/agreements": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetAgreements",
        "summary": "Retrieves agreements for the web form."
      }
    },
    "/widgets/{widgetId}/auditTrail": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetAuditTrail",
        "summary": "Retrieves the audit trail of a web form identified by widgetId."
      }
    },
    "/widgets/{widgetId}/combinedDocument": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetCombinedDocument",
        "summary": "Retrieves a single combined PDF document for the documents associated with a web form."
      }
    },
    "/widgets/{widgetId}/combinedDocument/url": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetCombinedDocumentUrl",
        "summary": "Retrieves url of all visible pages of all the documents associated with a web form."
      }
    },
    "/widgets/{widgetId}/documents": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetDocuments",
        "summary": "Retrieves the IDs of the documents associated with web form."
      }
    },
    "/widgets/{widgetId}/documents/imageUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetAllDocumentsImageUrls",
        "summary": "Retrieves image urls of all visible pages of a document associated with a web form."
      }
    },
    "/widgets/{widgetId}/documents/{documentId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetDocumentInfo",
        "summary": "Retrieves the file stream of a document of a web form."
      }
    },
    "/widgets/{widgetId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getEvents3",
        "summary": "Retrieves the events information for a web form."
      }
    },
    "/widgets/{widgetId}/formData": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "description": "CSV/JSON file stream containing form data information",
        "operationId": "getWidgetFormData",
        "summary": "Retrieves data entered by the user into interactive form fields at the time they signed the web form"
      }
    },
    "/widgets/{widgetId}/formFields": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetFormFields",
        "summary": "Retrieves form fields for a web form."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateFormFields3",
        "summary": "Updates details of form fields of a web form."
      }
    },
    "/widgets/{widgetId}/me": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetInfoForUser",
        "summary": "Retrieves the web form information related to the api caller"
      }
    },
    "/widgets/{widgetId}/me/note": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetNoteForApiUser",
        "summary": "Retrieves the latest note of a web form for the API user."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidgetNoteForApiUser",
        "summary": "Updates the latest note of a web form for the API user."
      }
    },
    "/widgets/{widgetId}/me/visibility": {
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidgetVisibility",
        "summary": "Updates the visibility of web form."
      }
    },
    "/widgets/{widgetId}/members": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getAllWidgetMembers",
        "summary": "Retrieves detailed member info along with IDs for different types of participants."
      }
    },
    "/widgets/{widgetId}/members/ccParticipants": {
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidgetCCParticipantEmail",
        "summary": "Updates the Email of CC participant of a Web Form identified by WidgetId in the path."
      }
    },
    "/widgets/{widgetId}/members/participantSets/{participantSetId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getParticipantSet1",
        "summary": "Retrieves the participant set of a web form identified by widgetId in the path."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidgetParticipantSetEmail",
        "summary": "Updates the Email of participant set of a Web Form identified by WidgetId in the path."
      }
    },
    "/widgets/{widgetId}/members/participantSets/{participantSetId}/participants/{participantId}/securityOptions": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetSecurityOptionsForParticipation",
        "summary": "Retrieves the security options for a particular participant."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidgetSecurityOptionsForParticipation",
        "summary": "Updates the security options for a particular participant."
      }
    },
    "/widgets/{widgetId}/members/share": {
      "post": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "createShareOnWidget",
        "summary": "Share a web form with someone."
      }
    },
    "/widgets/{widgetId}/state": {
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "description": "This endpoint can be used by creator of the web form to transition between the states of web form. An allowed transition would follow any of the following sequence :  DRAFT->AUTHORING->ACTIVE, ACTIVE<->INACTIVE, DRAFT->CANCELLED.",
        "operationId": "updateWidgetState",
        "summary": "Updates the state of a web form identified by widgetId in the path."
      }
    },
    "/widgets/{widgetId}/views": {
      "post": {
        "security": [
          {
            "oauth2": [
              "widget_read",
              "user_login"
            ]
          }
        ],
        "operationId": "getWidgetView",
        "summary": "Retrieves the requested views for a web form."
      }
    },
    "/workflows": {
      "get": {
        "security": [
          {
            "oauth2": [
              "workflow_read"
            ]
          }
        ],
        "operationId": "getWorkflows",
        "summary": "Retrieves workflows for a user."
      }
    },
    "/workflows/{workflowId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "workflow_read"
            ]
          }
        ],
        "operationId": "getWorkflowInfo",
        "summary": "Retrieves the details of a workflow."
      }
    }
  },
  "components": {
  }
}