{
  "openapi": "3.0.0",
  "info": {
    "title": "secure.na3.adobesign.com",
    "version": "6.0.0"
  },
  "servers": [
    {
      "url": "https://secure.na3.adobesign.com/api/rest/v6"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getUsers",
        "summary": "Retrieves all the users in an account."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "createUser",
        "summary": "Creates a new user in the Acrobat Sign system"
      }
    },
    "/users/{userId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getUserDetail",
        "summary": "Retrieves detailed information about the user in the caller account."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "modifyUser",
        "summary": "Update an user."
      }
    },
    "/users/{userId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getUserEvents",
        "summary": "Retrieves all events for user"
      }
    },
    "/users/{userId}/groups": {
      "get": {
        "security": [
          {
            "oauth2": [
              "user_read"
            ]
          }
        ],
        "operationId": "getGroupsOfUser",
        "summary": "Retrieves the groups of the user."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "updateGroupsOfUser",
        "summary": "Updates the groups of the user."
      }
    },
    "/users/{userId}/locale": {
      "put": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "modifyUserLocale",
        "summary": "Updates the user locale."
      }
    },
    "/users/{userId}/state": {
      "put": {
        "security": [
          {
            "oauth2": [
              "user_write"
            ]
          }
        ],
        "operationId": "modifyUserState",
        "summary": "Activate/Deactivate a given user."
      }
    },
    "/users/{userId}/views": {
      "post": {
        "security": [
          {
            "oauth2": [
              "user_read",
              "user_login"
            ]
          }
        ],
        "operationId": "getUserViews",
        "summary": "Retrieves the URL of manage, account settings and user profile page."
      }
    }
  },
  "components": {
  }
}
