{
  "openapi": "3.0.0",
  "info": {
    "title": "secure.na3.adobesign.com",
    "version": "6.0.0"
  },
  "servers": [
    {
      "url": "https://secure.na3.adobesign.com/api/rest/v6"
    }
  ],
  "paths": {
    "/widgets": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgets",
        "summary": "Retrieves web forms for a user."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "description": "This is a primary endpoint which is used to create a new web form. You can create a web form in one of the 3 mentioned states: a) <b>DRAFT</b> - to incrementally build the web form, b) <b>AUTHORING</b> - to add/edit form fields in the web form, c) <b>ACTIVE</b> - to immediately host the web form. You can use the PUT /widgets/{widgetId}/state endpoint to transition a web form between the above mentioned states. An allowed transition would follow the any of the following se[...]",
        "operationId": "createWidget",
        "summary": "Creates a web form and and returns the widgetId in the response to the client."
      }
    },
    "/widgets/{widgetId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetInfo",
        "summary": "Retrieves the details of a web form."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidget",
        "summary": "Updates a web form."
      }
    },
    "/widgets/{widgetId}/agreements": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetAgreements",
        "summary": "Retrieves agreements for the web form."
      }
    },
    "/widgets/{widgetId}/auditTrail": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetAuditTrail",
        "summary": "Retrieves the audit trail of a web form identified by widgetId."
      }
    },
    "/widgets/{widgetId}/combinedDocument": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetCombinedDocument",
        "summary": "Retrieves a single combined PDF document for the documents associated with a web form."
      }
    },
    "/widgets/{widgetId}/combinedDocument/url": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetCombinedDocumentUrl",
        "summary": "Retrieves url of all visible pages of all the documents associated with a web form."
      }
    },
    "/widgets/{widgetId}/documents": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetDocuments",
        "summary": "Retrieves the IDs of the documents associated with web form."
      }
    },
    "/widgets/{widgetId}/documents/imageUrls": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetAllDocumentsImageUrls",
        "summary": "Retrieves image urls of all visible pages of a document associated with a web form."
      }
    },
    "/widgets/{widgetId}/documents/{documentId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetDocumentInfo",
        "summary": "Retrieves the file stream of a document of a web form."
      }
    },
    "/widgets/{widgetId}/events": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getEvents",
        "summary": "Retrieves the events information for a web form."
      }
    },
    "/widgets/{widgetId}/formData": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "description": "CSV/JSON file stream containing form data information",
        "operationId": "getWidgetFormData",
        "summary": "Retrieves data entered by the user into interactive form fields at the time they signed the web form"
      }
    },
    "/widgets/{widgetId}/formFields": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetFormFields",
        "summary": "Retrieves form fields for a web form."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateFormFields",
        "summary": "Updates details of form fields of a web form."
      }
    },
    "/widgets/{widgetId}/me": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetInfoForUser",
        "summary": "Retrieves the web form information related to the api caller"
      }
    },
    "/widgets/{widgetId}/me/note": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetNoteForApiUser",
        "summary": "Retrieves the latest note of a web form for the API user."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidgetNoteForApiUser",
        "summary": "Updates the latest note of a web form for the API user."
      }
    },
    "/widgets/{widgetId}/me/visibility": {
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidgetVisibility",
        "summary": "Updates the visibility of web form."
      }
    },
    "/widgets/{widgetId}/members": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getAllWidgetMembers",
        "summary": "Retrieves detailed member info along with IDs for different types of participants."
      }
    },
    "/widgets/{widgetId}/members/ccParticipants": {
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidgetCCParticipantEmail",
        "summary": "Updates the Email of CC participant of a Web Form identified by WidgetId in the path."
      }
    },
    "/widgets/{widgetId}/members/participantSets/{participantSetId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getParticipantSet",
        "summary": "Retrieves the participant set of a web form identified by widgetId in the path."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidgetParticipantSetEmail",
        "summary": "Updates the Email of participant set of a Web Form identified by WidgetId in the path."
      }
    },
    "/widgets/{widgetId}/members/participantSets/{participantSetId}/participants/{participantId}/securityOptions": {
      "get": {
        "security": [
          {
            "oauth2": [
              "widget_read"
            ]
          }
        ],
        "operationId": "getWidgetSecurityOptionsForParticipation",
        "summary": "Retrieves the security options for a particular participant."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "updateWidgetSecurityOptionsForParticipation",
        "summary": "Updates the security options for a particular participant."
      }
    },
    "/widgets/{widgetId}/members/share": {
      "post": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "operationId": "createShareOnWidget",
        "summary": "Share a web form with someone."
      }
    },
    "/widgets/{widgetId}/state": {
      "put": {
        "security": [
          {
            "oauth2": [
              "widget_write"
            ]
          }
        ],
        "description": "This endpoint can be used by creator of the web form to transition between the states of web form. An allowed transition would follow any of the following sequence :  DRAFT->AUTHORING->ACTIVE, ACTIVE<->INACTIVE, DRAFT->CANCELLED.",
        "operationId": "updateWidgetState",
        "summary": "Updates the state of a web form identified by widgetId in the path."
      }
    },
    "/widgets/{widgetId}/views": {
      "post": {
        "security": [
          {
            "oauth2": [
              "widget_read",
              "user_login"
            ]
          }
        ],
        "operationId": "getWidgetView",
        "summary": "Retrieves the requested views for a web form."
      }
    }
  },
  "components": {
  }
}
